- name: Enable copr repos
  command: dnf copr -y enable {{ item }}
  args:
    warn: false
  loop:
    - jcrd/snapback
    - rockowitz/ddcutil

- name: Install packages
  dnf:
    name:
      - ddcutil
      - nvme-cli
      - snapback

- name: Enable systemd units from packages
  systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - snapback.timer

- name: Copy i2c udev rule
  copy:
    src: /usr/share/ddcutil/data/45-ddcutil-i2c.rules
    dest: /etc/udev/rules.d
    mode: preserve
  become: true

- name: Create i2c group
  group:
    name: i2c
    system: true
  become: true

- name: Add user to i2c group
  user:
    name: '{{ user }}'
    groups: i2c
    append: true
  become: true
