- name: Clone dotfile repos
  git:
    repo: 'https://github.com/jcrd/{{ item.repo }}'
    dest: '{{ configdir }}/{{ item.dest }}'
    update: false
  loop:
    - {repo: 'configs', dest: 'configs'}
    - {repo: 'neovim-config', dest: 'nvim'}
    - {repo: 'zsh-config', dest: 'zsh'}

- name: Configure dotfiles
  shell: >
    cd {{ configdir }}/{{ item }} &&
    source ../zsh/zshenv &&
    ./configure
  args:
    executable: /usr/bin/zsh
  loop:
    - configs
    - nvim
    - zsh
