- name: Download rpmfusion gpg keys
  rpm_key: key={{ item }}
  loop:
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Enable rpmfusion repos
  dnf:
    name:
      - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ releasever }}.noarch.rpm'
      - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ releasever }}.noarch.rpm'

- name: Download microsoft gpg key
  rpm_key: key='https://packages.microsoft.com/keys/microsoft.asc'

- name: Enable vscode repo
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: preserve

- name: Enable notion-repackaged repo
  copy:
    src: notion-repackaged.repo
    dest: /etc/yum.repos.d/notion-repackaged.repo
    mode: preserve

- name: Enable copr repos
  command: dnf copr -y enable {{ item }}
  args:
    warn: false
  loop:
    - jcrd/sessiond
    - jcrd/awesome-luajit-nightly
    - jcrd/clipped
    - jcrd/nicety
    - jcrd/passless
    - jcrd/toolboxcutter

- name: Install packages
  dnf:
    name:
      - ImageMagick
      - abduco
      - aria2
      - arp-scan
      - atool
      - awesome
      - byzanz
      - clipped
      - code
      - colordiff
      - copr-cli
      - d-feet
      - direnv
      - fedora-packager
      - fedora-review
      - ffmpegthumbnailer
      - firefox
      - flatpak
      - fontawesome-fonts
      - fzf
      - gcolor2
      - git
      - git-subtree
      - gucharmap
      - htop
      - i3lock
      - iotop
      - kernel-tools
      - kitty
      - liberation-fonts
      - lm_sensors
      - luarocks
      - maim
      - mosh
      - mpv
      - mupdf
      - neovim
      - nicety
      - notion-app-enhanced
      - passless
      - picom
      - pinentry-gtk
      - progress
      - ps_mem
      - python-neovim
      - python-pillow
      - python-tasklib
      - ranger
      - redshift
      - ripgrep
      - rlwrap
      - rofi
      - rpkg
      - sessiond
      - slop
      - sshfs
      - sshpass
      - strace
      - sxiv
      - syncthing
      - task
      - tigervnc
      - tmux
      - toolbox
      - toolboxcutter
      - xclip
      - xev
      - xorg-x11-server-Xephyr
      - xprop
      - zoxide
      - zsh

- name: Enable systemd units from packages
  systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - nicety.service

- name: Enable firewalld services
  firewalld:
    service: "{{ item }}"
    state: enabled
  loop:
    - syncthing

- name: Configure nicety
  copy:
    src: nicety/rules.d/
    dest: /etc/nicety/rules.d
    mode: preserve
