- name: Download linrunner gpg key
  rpm_key:
    key: 'https://repo.linrunner.de/fedora/tlp/repos/RPM-GPG-KEY-tlp-fedora-{{ releasever }}-primary'

- name: Enable linrunner tlp repo
  dnf:
    name: 'https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ releasever }}.noarch.rpm'

- name: Install packages
  dnf:
    name:
      - akmod-acpi_call
      - powertop
      - tlp
      - upower

- name: Set acpi_call module to be loaded
  copy:
    content: acpi_call
    dest: /etc/modules-load.d/acpi_call.conf
    mode: 0644
